### ISSUE TITLE
how do i validate url

### ISSUE THREAD

**Issue by codenoid** [vladfaust/validations.cr#8]
is this string is url

**Comment by vladfaust** [comment]
It's not in the list of default rules because the implementation may vary. 

It's fairly easy to add custom rules: http://github.vladfaust.com/validations.cr/Validations.html#rule%28rule%29-macro.

In this case, it would be smth like:

```crystal
rule :url do |attr, value|
  unless value.nil?
    invalidate(attr, "must be an URL string") unless (URI.parse(value) rescue nil)
  end
end
```
